### ISSUE TITLE
High-performance it really ain't

### ISSUE THREAD

**Issue by eddelbuettel** [jeroen/protolite#1]
You may want to consider [RApiSerialize](http://dirk.eddelbuettel.com/code/rapiserialize.html) which, after all, was written for this purpose (and inherited from another HPC application).

See the [benchmark in my updated answer here](http://stackoverflow.com/questions/36808581/how-to-prevent-rcpp-from-evaluating-call-objects).

(I see the DESCRIPTION got edited. Good.  If it were to focus on, say, "smaller" or "light-weight" it may be truthful.  "Fast" it ain't.)

**Comment by jeroen** [comment]
The `serialize` stuff is only a fallback for non-data objects that cannot be serialized by protobuf. The 'optimized' refers to the implementation of the protobuf serializer:

``` r
> library(ggplot2)
> data(diamonds)
> system.time(RProtoBuf::serialize_pb(diamonds, NULL))
   user  system elapsed 
  0.043   0.001   0.044 
> system.time(protolite::serialize_pb(diamonds, NULL))
   user  system elapsed 
  0.008   0.000   0.008 
```

The difference is even larger for character vectors:

``` r
> x <- as.character(diamonds$cut)
> system.time(protolite::serialize_pb(x, NULL))
   user  system elapsed 
  0.023   0.002   0.025 
> system.time(RProtoBuf::serialize_pb(x, NULL))
   user  system elapsed 
  6.525   0.029   6.555 
```

**Comment by eddelbuettel** [comment]
Fine. You still have no reason to use the Rcpp::Environment kludge _to serialize to raw_ given that a _dedicated C implementation_ exists.

But your package so I don't give a fiddle.
