### ISSUE TITLE
Not able to install protolite 2.1 version

### ISSUE THREAD

**Issue by dipaksavate** [jeroen/protolite#15]
Ending up with below error

Error: package or namespace load failed for ‘protolite’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/R/libs/3.6/00LOCK-protolite/00new/protolite/libs/protolite.so':
 /R/libs/3.6/00LOCK-protolite/00new/protolite/libs/protolite.so: undefined symbol: _ZNK6google8protobuf11MessageLite25InitializationErrorStringB5cxx11Ev
Error: loading failed
Execution halted
ERROR: loading failed

Trying to install it on CentOS7. using gcc 7.4.0 with latest Rcpp. Any help will be highly appreciated.

**Comment by jeroen** [comment]
You're using a `gcc` that uses a different ABI than the one that ships with centos, and therefore is not compatible with the version of `protobuf-devel` that comes with CentOS.

The best way is to compile this package using the g++ that comes with centos, i.e. `/usr/bin/g++`. 

Alternatively you can use a more recent gcc that you have installed from the "Red Hat Developer Toolset" repository, which has been configured with the correct ABI.

If you really want to compile with your custom gcc,  try adding the following line to your `~/.R/Makevars` file:

```
CPPFLAGS=-D _GLIBCXX_USE_CXX11_ABI
```

More docs here: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
