### ISSUE TITLE
license status: compatible with Apache 2.0 project?

### ISSUE THREAD

**Issue by mhaberler** [jeroen/protolite#18]
@jeroen I am considering reusing your geobuf de/encoder in an [Apache2.0 licensed project](https://github.com/sewenew/redis-protobuf/blob/master/LICENSE)

is that ok for you? 

best regards
Michael

**Comment by jeroen** [comment]
Yes, all code I have written is available under MIT license.

https://github.com/jeroen/protolite/blob/5483e4876bcb45eaf44736afdfd7b203e989724d/DESCRIPTION#L14

**Comment by mhaberler** [comment]
thanks, appreciated!
