### ISSUE TITLE
Support geobuf (geojson protobuf)

### ISSUE THREAD

**Issue by jeroen** [jeroen/protolite#2]
See https://github.com/mapbox/geobuf

**Comment by sckott** [comment]
there's an awesome geojson list https://github.com/tmcw/awesome-geojson

**Comment by sckott** [comment]
- good place if you want to make any geojson on a map http://geojson.io/
- geojson spec http://geojson.org/geojson-spec.html
- you can simply copy paste from the spec examples here http://geojson.org/geojson-spec.html#appendix-a-geometry-examples for small examples of each type
- us states as geojson https://github.com/glynnbird/usstatesgeojson
- there's an awesome geojson list https://github.com/tmcw/awesome-geojson

**Comment by jeroenooms** [comment]
thanks!

**Comment by jeroen** [comment]
Starting a new branch: https://github.com/jeroenooms/protolite/tree/geobuf

**Comment by jeroen** [comment]
Some notes from analyzing the @mourner JavaScript implementation:
- The `uint32 dimensions = 2` field sets the size of a single **point**. Default is 2 (e.g lat+lon).
- Coordinate numbers are stored as `(int64) y = x * 10^e` where `e` is stored in **precision**. Hence  `0.123` with default precision of `6` gets stored as `123000`.
- The `coords` array contains the **deltas** of the coordinates by dimension. So `[[100,20], [110, 5]]`  becomes `100,2,10,-15`.
- Property **keys** are stored globally in `repeated string keys` and are referred by their index in `custom_properties`.
- Propery **values** are stored inside `message Value: {oneof value_type}`.
- For 3 deep structures, **lengths** stores size of each line. So `[[[1,2], [3,4]], [[5,6],[3,3], [1,2]]]` is stored as `dimensions = 2` and `lengths = 2,3` and `coords = 1,2,2,2,2,2,-2,-3,-2,-1`.

**Comment by jeroen** [comment]
@sckott I implemented the parser. Could you give this a try? To test, take an arbitrary geojson file and use the npm module to convert it to a proto buffer:

```
npm install geobuf
json2geobuf geojson.json > geobuf.pb
```

You can read `geobuf.pb` in R using `protolite::unserialize_geobuf` or `protolite::geobuf2json`.

**Comment by jeroen** [comment]
This is now fully implemented in protolite 1.4/
